version: '3.3'
services:
  app:
    container_name: beverage-store-spring-boot
    image: alnoman/beverage-store-spring-boot
    build: ./
    environment:
      - DB_HOST=dbpostgresql
      - RABBIT_HOST=rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      - rabbitmq

  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=tester
      - POSTGRES_USER=tester
      - POSTGRES_DB=beveragestoreboot

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"