spring:
  application:
    name: beverage-store-spring-boot
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:5432/beveragestoreboot'
    username: tester
    password: tester
    driver-class-name: org.postgresql.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    hikari:
      connection-test-query: 'SELECT 1'
      maximum-pool-size: 10
      properties:
        hibernate:
          jdbc:
            time_zone: 'UTC'
    # =============================================================================================
    # = Flyway
    # =============================================================================================
    flyway.clean-on-validation-error: false
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
  rabbitmq:
    host: ${RABBIT_HOST}
server:
  port: 8080
beveragestore:
  rabbitmq:
    exchange: ${BEVERAGE_STORE_EXCHANGE} #'beverage_store_exchange'
    queue: ${BEVERAGE_STORE_QUEUE} #'beverage_store_queue'
    routing_key: ${BEVERAGE_STORE_ROUTING_KEY} #'beverage_store_routing_key'
logging:
  level:
    ROOT: info

management:
  endpoints:
    web:
      exposure:
        include: health, loggers, metrics, mappings
